{{- if .Values.clusterGroup.isHubCluster }}
{{- if .Values.global.originURL }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-secret-s3-anomaly
  namespace: ml-development
spec:
  data:
    - conversionStrategy: None
      match:
        remoteRef:
          remoteKey: pushsecrets/s3-anomaly
          property: AWS_ACCESS_KEY_ID
        secretKey: AWS_ACCESS_KEY_ID
    - conversionStrategy: None
      match:
        remoteRef:
          remoteKey: pushsecrets/s3-anomaly
          property: AWS_SECRET_ACCESS_KEY
        secretKey: AWS_SECRET_ACCESS_KEY
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    secret:
      name: anomaly-detection
  updatePolicy: Replace
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: s3-anomaly-external-secret
  namespace: manuela-data-lake
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: s3-anomaly
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: "pushsecrets/s3-anomaly"
{{- end }}
{{- end }}
