{{- if .Values.clusterGroup.isHubCluster }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-secret-kafka-user
  namespace: manuela-data-lake
spec:
  data:
    - conversionStrategy: None
      match:
        remoteRef:
          remoteKey: pushsecrets/kafka-user
          property: password
        secretKey: password
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    secret:
      name: kafka-user
  updatePolicy: Replace
{{- end }}
