apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: factory-to-central-mm2
  namespace: factory-messaging
spec:
  version: 3.7.0
  replicas: 1
  connectCluster: production-kafka-cluster
  clusters:
    - alias: production-kafka-cluster
      bootstrapServers: 'prod-kafka-cluster-kafka-bootstrap-manuela-data-lake.{{ .Values.global.hubClusterDomain }}:443'
      #bootstrapServers: 'bootstrap-manuela-data-lake-kafka-cluster.apps.industrial-factory-1.blueprints.rhecoeng.com:443'
      tls:
        trustedCertificates:
        - certificate: ca.crt
          secretName: prod-kafka-cluster-cluster-ca-cert
      authentication:
        type: scram-sha-512
        username: cluster-a-user
        passwordSecret:
          secretName: kafka-hub-user
          password: password
    - alias: factory-kafka-cluster
      bootstrapServers: 'factory-kafka-cluster-kafka-bootstrap.factory-messaging.svc:9092'
      # -1 means it will use the default replication factor configured in the broker
      config:
        config.storage.replication.factor: -1
        offset.storage.replication.factor: -1
        status.storage.replication.factor: -1
  mirrors:
    - sourceCluster: factory-kafka-cluster
      targetCluster: production-kafka-cluster
      sourceConnector:
        tasksMax: 1
        config:
          # -1 means it will use the default replication factor configured in the broker
          replication.factor: -1
          offset-syncs.topic.replication.factor: -1
          sync.topic.acls.enabled: 'false'
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: -1
      checkpointConnector:
        tasksMax: 1
        config:
          checkpoints.topic.replication.factor: -1
          sync.group.offsets.enabled: "false"
          refresh.groups.interval.seconds: 600
      topicsPattern: .*
      groupsPattern: .*
